-- FUNCION DE VALOR PI
SELECT PI() AS Pi;

-- FUNCION DE REDONDEO DE CIFRAS
SELECT CEILING($123.90) AS redondeo, CEILING(-123.45) AS redondeo_negativo;

--FUNCION PARA ELIMINAR DECIMALES
SELECT FLOOR(123.45), FLOOR(-123.50);

--REDONDEO DE CIFRAS CON APROXIMACION
SELECT ROUND(123.5666, 4);

-- CALCULO DE POTENCIACION DE UNA CIFRA
SELECT POWER(8,3);

-- FUNCION RAND() PARA NUMEROS ALEATORIOS
SELECT RAND()*(100-1) AS Aleatorio;
SELECT FLOOR(RAND()*(100-1)) AS Aleatorio;

-- CALCULO DE SENO Y COSENO DE UN ANGULO
SELECT FLOOR(SIN(45)) AS Seno, FLOOR(COS(45)) AS Coseno;

-- CALCULO DE RAIZ CUADRADA
SELECT SQRT(64) AS Raiz;